cats = '''CREATE (:Category {name: "amateur"})
CREATE (:Category {name: "anal"})
CREATE (:Category {name: "asian"})
CREATE (:Category {name: "ass"})
CREATE (:Category {name: "ass to mouth"})
CREATE (:Category {name: "babe"})
CREATE (:Category {name: "bbw"})
CREATE (:Category {name: "bdsm"})
CREATE (:Category {name: "big dick"})
CREATE (:Category {name: "big tits"})
CREATE (:Category {name: "bisexual"})
CREATE (:Category {name: "bizarre"})
CREATE (:Category {name: "blonde"})
CREATE (:Category {name: "blowjob"})
CREATE (:Category {name: "bondage"})
CREATE (:Category {name: "brazilian"})
CREATE (:Category {name: "brunette"})
CREATE (:Category {name: "bukkake"})
CREATE (:Category {name: "casting"})
CREATE (:Category {name: "celebrity"})
CREATE (:Category {name: "chinese"})
CREATE (:Category {name: "college"})
CREATE (:Category {name: "compilation"})
CREATE (:Category {name: "creampie"})
CREATE (:Category {name: "cuckold"})
CREATE (:Category {name: "cumshot"})
CREATE (:Category {name: "cunnilingus"})
CREATE (:Category {name: "daddy"})
CREATE (:Category {name: "deep Throat"})
CREATE (:Category {name: "double penetration"})
CREATE (:Category {name: "ebony"})
CREATE (:Category {name: "european"})
CREATE (:Category {name: "exgirlfriend"})
CREATE (:Category {name: "exhibitionism"})
CREATE (:Category {name: "facial"})
CREATE (:Category {name: "fat"})
CREATE (:Category {name: "feet"})
CREATE (:Category {name: "fetish"})
CREATE (:Category {name: "first Time"})
CREATE (:Category {name: "fisting"})
CREATE (:Category {name: "for women"})
CREATE (:Category {name: "gangbang"})
CREATE (:Category {name: "gloryhole"})
CREATE (:Category {name: "groupsex"})
CREATE (:Category {name: "gym"})
CREATE (:Category {name: "hairy"})
CREATE (:Category {name: "handjob"})
CREATE (:Category {name: "hardcore"})
CREATE (:Category {name: "hentai"})
CREATE (:Category {name: "homemade"})
CREATE (:Category {name: "incest"})
CREATE (:Category {name: "indian"})
CREATE (:Category {name: "interracial"})
CREATE (:Category {name: "japanese"})
CREATE (:Category {name: "latina"})
CREATE (:Category {name: "lesbian"})
CREATE (:Category {name: "massage"})
CREATE (:Category {name: "masturbation"})
CREATE (:Category {name: "mature"})
CREATE (:Category {name: "military"})
CREATE (:Category {name: "milf"})
CREATE (:Category {name: "mmf"})
CREATE (:Category {name: "office"})
CREATE (:Category {name: "old and young"})
CREATE (:Category {name: "oral"})
CREATE (:Category {name: "orgy"})
CREATE (:Category {name: "outdoor"})
CREATE (:Category {name: "petite"})
CREATE (:Category {name: "piss"})
CREATE (:Category {name: "pornstars"})
CREATE (:Category {name: "pov"})
CREATE (:Category {name: "pregnant"})
CREATE (:Category {name: "prolapse"})
CREATE (:Category {name: "public"})
CREATE (:Category {name: "redhead"})
CREATE (:Category {name: "russian"})
CREATE (:Category {name: "shemale"})
CREATE (:Category {name: "sleeping"})
CREATE (:Category {name: "small dick"})
CREATE (:Category {name: "small tits"})
CREATE (:Category {name: "solo"})
CREATE (:Category {name: "squirt"})
CREATE (:Category {name: "strapon"})
CREATE (:Category {name: "striptease"})
CREATE (:Category {name: "teacher"})
CREATE (:Category {name: "teen"})
CREATE (:Category {name: "threesome"})
CREATE (:Category {name: "toys"})
CREATE (:Category {name: "uniform"})
CREATE (:Category {name: "vintage"})
CREATE (:Category {name: "voyeur"})
CREATE (:Category {name: "webcam"})
CREATE (:Category {name: "69"})
CREATE (:Category {name: "twink"})
CREATE (:Category {name: "bear"})
CREATE (:Category {name: "otter"})
CREATE (:Category {name: "straight"})
CREATE (:Category {name: "bearback"})
CREATE (:Category {name: "hunks"})
CREATE (:Category {name: "black"})
CREATE (:Category {name: "latino"})
CREATE (:Category {name: "monster cock"})
CREATE (:Category {name: "locker room"})
CREATE (:Category {name: "sports"})'''